# Default theme for Lubuntu by The Lubuntu Artwork Team:
# Rafael Laguna and Alexander Andjelkovic
# Based on Radiance. GPL2 / Open Source licensed
# More info at: https://launchpad.net/~lubuntu-art

[Desktop Entry]
Name=Lubuntu
Type=X-GNOME-Metatheme
Comment=Default theme for Lubuntu
Encoding=UTF-8

[X-GNOME-Metatheme]
GtkTheme=Lubuntu-default
IconTheme=Lubuntu
CursorTheme=DMZ-Black
CursorSize=24
NotificationTheme=ubuntu
MetacityTheme=Lubuntu-default
ButtonLayout=close,minimize,maximize:
